# Generated by Django 5.1.6 on 2026-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('Type', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Health', 'Health'), ('Education', 'Education')], max_length=50)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
